version: '3.7'
services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DOMAIN_NAME=http://192.168.1.106:8441
    ports:
      - 8441:80
    volumes:
      - wallabagimages:/var/www/wallabag/web/assets/images
      - wallabagdata:/var/www/wallabag/data
     
    depends_on:
     - db
     - redis
  db:
    image: mariadb
    container_name: wallabag-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - TZ=Asia/Shanghai
    volumes:
      - wallabagdb:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: wallabag-redis
    restart: always
volumes:
  wallabagdb:
  wallabagimages:
  wallabagdata:
  
networks:
  wallabag:
