version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: nextcloud-mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always

  app:
    build: ./nextcloud-alpine
    container_name: nextcloud-main
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ${nextcloud_main_path}:/nextcloud_data
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - PHP_UPLOAD_LIMIT=$PHP_UPLOAD_LIMIT
      # - NEXTCLOUD_DATA_DIR=$NEXTCLOUD_DATA_DIR
      - NEXTCLOUD_TRUSTED_DOMAINS=$NEXTCLOUD_TRUSTED_DOMAINS
      - SMTP_HOST=$SMTP_HOST
      - SMTP_SECURE=$SMTP_SECURE
      - SMTP_PORT=$SMTP_PORT
      - SMTP_AUTHTYPE=$SMTP_AUTHTYPE
      - SMTP_NAME=$SMTP_NAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS
      - MAIL_DOMAIN=$MAIL_DOMAIN
    depends_on:
      - db
      - redis

  web:
    build: ./web
    container_name: nextcloud-web
    restart: always
    ports:
      - ${web_port}:80
    volumes:
      - nextcloud:/var/www/html:ro 
    depends_on:
      - app

  cron:
    build: ./nextcloud-alpine
    container_name: nextcloud-cron
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
  
networks:
  nextcloud:
