version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: nextcloud-mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always

  app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-main
    restart: always
    volumes:
      - nextcloud:/var/www/html
      # 这个路径是映射到本地的,如果直接映射html文件夹，cron会失效，至少我的群晖是这样的。
      - $path:/nextcloud_data
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      ## 更改数据文件安装位置 默认是 /var/www/html/data
      # - NEXTCLOUD_DATA_DIR=$NEXTCLOUD_DATA_DIR
      - NEXTCLOUD_TRUSTED_DOMAINS=$domains                   # 定义受信任的域名,可以是多个，用空格隔开。
      ## 这里不用的话就注释掉,或者直接不填写。我自用的话就全打开了。
      - SMTP_HOST=$SMTP_HOST                                 # SMTP服务器的主机名
      - SMTP_SECURE=$SMTP_SECURE                             # 设置为ssl以使用SSL，或设置为tls以使用STARTTLS
      - SMTP_PORT=$SMTP_PORT                                 # 默认：SSL 为 465，不安全连接为25 , SMTP 连接可选端口。使用 587 作为 STARTTLS 的备用端口。
      - SMTP_AUTHTYPE=$SMTP_AUTHTYPE                         # 默认：LOGIN 用于身份验证的方法。如果不需要身份验证，请使用 PLAIN。
      - SMTP_NAME=$SMTP_NAME                                 # 默认为空：smtp 身份验证的用户名。
      - SMTP_PASSWORD=$SMTP_PASSWORD                         # 默认为空：smtp 身份验证的密码。
      - MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS                 # 默认情况下未设置，邮箱 @ 之前的字段
      - MAIL_DOMAIN=$MAIL_DOMAIN                             # 默认情况下未设置,就是发送邮箱的尾缀，如 qq.com
    depends_on:
      - db
      - redis

  web:
    build: ./web
    container_name: nextcloud-web
    restart: always
    ports:
      - ${web_port}:80
    volumes:
      - nextcloud:/var/www/html:ro 
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-cron
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
  
networks:
  nextcloud:
