version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: nextcloud-mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    networks:
      - nextcloud

  app:
    build: ./nextcloud
    container_name: nextcloud-main
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ${nextcloud_main_path}:/nextcloud_data
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - PHP_UPLOAD_LIMIT=$PHP_UPLOAD_LIMIT
      - NEXTCLOUD_DATA_DIR=$NEXTCLOUD_DATA_DIR
      - NEXTCLOUD_TRUSTED_DOMAINS=$NEXTCLOUD_TRUSTED_DOMAINS
      - SMTP_HOST=$SMTP_HOST
      - SMTP_SECURE=$SMTP_SECURE
      - SMTP_PORT=$SMTP_PORT
      - SMTP_AUTHTYPE=$SMTP_AUTHTYPE
      - SMTP_NAME=$SMTP_NAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS
      - MAIL_DOMAIN=$MAIL_DOMAIN
    networks:
      - nextcloud
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx
    container_name: nextcloud-web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    ports:
      - ${loacl_port}:80
    networks:
      - caddy
      - nextcloud
    depends_on:
      - app

  cron:
    build: ./nextcloud
    container_name: nextcloud-cron
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    networks:
      - nextcloud
    depends_on:
      - db
      - redis

  web:
    #image: ./caddy-dnspodcn
    image: yangtudou/caddy-dnspodcn
    container_name: caddy-proxy
    ports:
      - ${proxy_https_port}:${proxy_https_port}
      - ${proxy_http_port}:${proxy_http_port}
    networks:
      - caddy
      - nextcloud
    volumes:
      - $loacl_certs:/certs
      - $caddy_caddyfile:/etc/caddy
      - $caddy_data:/data
      - $caddy_config:/config
    restart: unless-stopped
    depends_on:
      - nginx

volumes:
  db:
  nextcloud:

networks:
  nextcloud:
  caddy:
    external: true
