services:
  traefik:
    image: library/traefik:v3.7
    container_name: traefik
    restart: unless-stopped

    ports:
      - 80:80
      - 443:443
    
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN} # cf-tunnel token
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
    
    volumes:
      - ./config/traefik.yml:/traefik.yml:ro # 配置文件
      - ./data:/data
    
    command:
      - --configFile=/traefik.yml
    
    depends_on:
      - docker-socket-proxy
    
    networks:
      - homelab-net


  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy
    restart: unless-stopped
    
    environment:
      CONTAINERS: 1
      EVENTS: 1
      INFO: 1
      VERSION: 1
      NETWORKS: 1
      POST: 0        # 禁止 Docker 写操作
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    networks:
      - homelab-net


networks:
  homelab-net:
    external: true