address: 0.0.0.0
port: 80
behindProxy: true
directory: /data
permissions: R
cors:
  enabled: true

users:
  - username: "webdav"
    # docker run --rm ghcr.io/hacdias/webdav:latest bcrypt "<明文密码>"
    password: ${PASSWORD}