version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - ${local_port}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: $wordpress_db_pwd
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: $wordpress_db_pwd
      MYSQL_ROOT_PASSWORD:: $mysql_root_pwd
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
