services:
  
  memos:
    image: neosmemo/memos:0.27.1
    container_name: memos
    restart: unless-stopped
        
    expose:
      - "5230"
    
    volumes:
      - ./data:/var/opt/memos
            
    environment:
      MEMOS_PORT: "5230"
      MEMOS_DRIVER: "sqlite"

    networks:
      - homelab-net

networks:
  homelab-net:
    external: true