services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped

    expose:
      - 3001
    
    volumes:
      - ./data:/app/data

    networks:
      - homelab-net

networks:
  homelab-net:
    external: true
