name: registry-sync demo

on:
  workflow_dispatch:

jobs:
  sync:
    name: registry-sync demo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Log in to Aliyun Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY_DOMAIN }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: registry-sync
        uses: yangtudou/registry-sync@main
        with:
          src: nginx:latest
          dst: ${{ secrets.ALIYUN_REGISTRY_DOMAIN }}/${{ secrets.ALIYUN_REGISTRY_SPACE_NAME }}
          platform: linux/amd64
          concurrency: '4'
          retries: '3'
