name: Registry Sync demo

on:
  workflow_dispatch:

# 最小权限原则
permissions:
  contents: read
  packages: write

jobs:
  sync:
    name: main 分支
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false

      # 生成临时配置
      - name: Generate config
        shell: bash
        env:
          ALIYUN_REGISTRY_SPACE_NAME: ${{ secrets.ALIYUN_REGISTRY_SPACE_NAME }}
          ALIYUN_REGISTRY_DOMAIN: ${{ secrets.ALIYUN_REGISTRY_DOMAIN }}
          SYNC_CONFIG_TEMPLATE: toAliCR.yaml
        run: |
          set -euo pipefail

          envsubst < "${SYNC_CONFIG_TEMPLATE}" > config.yaml

          chmod 600 config.yaml

      # 登录 ACR
      - name: Login ACR
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY_DOMAIN }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}


      # 执行同步
      - name: Sync images
        uses: yyysay/registry-sync@main
        with:
          config: ./config.yaml

      # 清理
      - name: Cleanup
        if: always()
        run: |
          rm -f config.yaml
