name: Sync Docker Images To Aliyun

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  sync:
    name: Sync Images
    runs-on: ubuntu-latest

    env:
      ALIYUN_REGISTRY_SPACE_NAME: ${{ secrets.ALIYUN_REGISTRY_SPACE_NAME }}
      
      

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: 动态生成 auth.yaml
        env:
          ALIYUN_REGISTRY_DOMAIN: ${{ secrets.ALIYUN_REGISTRY_DOMAIN }}
          ALIYUN_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
          ALIYUN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
        run: |
          cat <<EOF > auth.yaml
          ${ALIYUN_REGISTRY_DOMAIN}:
            username: ${ALIYUN_USERNAME}
            password: ${ALIYUN_PASSWORD}
          EOF

      - name: 同步镜像
        uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml # 登入信息
          images_file: ./images.json # 映射
          version: latest # 如果没有指定
          proc: 4 # 并发
          os: linux
          arch: amd64

      - name: Cleanup Old Workflow Runs
        if: always()
        run: |
          RUN_IDS=$(gh api repos/${{ github.repository }}/actions/workflows/registry-sync.yml/runs --jq '.workflow_runs[] | select(.id != ${{ github.run_id }}) | .id')
          for id in $RUN_IDS; do gh api -X DELETE repos/${{ github.repository }}/actions/runs/$id; done
        env:
          GH_TOKEN: ${{ github.token }}
