name: Aliyun Registry Sync

on:
  workflow_dispatch:

jobs:
  sync:
    name: registry-sync demo
    runs-on: ubuntu-latest

    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false

      # - name: Scan Docker Compose & Generate images.txt
      #   run: |
      #     find . -type f \( -name "docker-compose.yaml" -o -name "docker-compose.yml" \) -print0 | \
      #     xargs -0 grep -h -E '^[[:space:]]*image:[[:space:]]*' | \
      #     sed -E 's/[[:space:]]*#.*$//' | \
      #     sed -E 's/^[[:space:]]*image:[[:space:]]*//' | \
      #     sed -E 's/^["'\'']//; s/["'\'']$//' | \
      #     grep -v '^$' | \
      #     sort -u > images.txt
          
      #     echo "=== 扫描完成，生成的 images.txt 内容如下 ==="
      #     cat images.txt
      
      - name: 登入私有仓库
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY_DOMAIN }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: 同步镜像文件
        uses: yangtudou/registry-sync@main
        with:
          dst-prefix: ${{ secrets.ALIYUN_REGISTRY_DOMAIN }}/${{ secrets.ALIYUN_REGISTRY_SPACE_NAME }}
          dst-flatten: true
