name: 🐋 隔空搬运 Forgejo 镜像到绿联 NAS

on:
  workflow_dispatch:

jobs:
  sync-image:
    runs-on: ubuntu-latest

    steps:
    - name: Connect to Tailscale
      uses: tailscale/github-action@v4
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Setup Crane
      uses: imjasonh/setup-crane@v0.3

    - name: Run Crane Copy
      run: |
        crane copy --platform linux/amd64 \
          codeberg.org/forgejo/forgejo:15 \
          registry.local.y3-3am.top/codeberg.org/forgejo/forgejo:15
