services:
  
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
        
    expose:
      - "5001"
        
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      
      - ${DOCKER_PATH}:${DOCKER_PATH}
        
    environment:
      DOCKGE_STACKS_DIR: ${DOCKER_PATH}

    networks:
      - homelab-net

networks:
  homelab-net:
    external: true

